
eureka:
  client:
    service-url:
      defaultZone: http://peer3:8763/eureka/
    healthcheck:
      enabled: true
    region: default
    availability-zones:
      default: default-zone
    enabled: true
    prefer-same-zone-eureka: true
    refresh:
      enable: false
  instance:
    hostname: localhost
    prefer-ip-address: false
    status-page-url: /info
    health-check-url: /health
    lease-renewal-interval-in-seconds: 30
    metadata-map:
      zone: zone1
server:
  port: 8082
spring:
  application:
    name: HELLO-SERVICE
  cloud:
    discovery:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: always